---
url: https://johncolinssf.prismic.io/api
# If specified this token is used for all "guest" requests
# token: ""
# OAuth2 configuration
client_id: "UpkL3wEAAII59lDc"
client_secret: "d926d832c748d0235b61bbf311e601f9"
